In [15]:
import pandas

In [16]:
from importlib import reload

In [123]:
import analyst

In [124]:
def stockpup_filename():
    return 'A_quarterly_financial_data.csv'

In [233]:
reload(analyst)

In [234]:
stockpup = analyst.Analyst(source='STOCKPUP', ticker='B').get_stock()

In [235]:
edgar = analyst.Analyst(source='EDGAR', ticker='A').get_stock()

In [236]:
edgar_raw = edgar.get_raw_data()

2021-06-06 02:33:37.353123::Ticker::A::Getting RAW data from A.csv::

In [237]:
stockpup_raw = stockpup.get_raw_data()

2021-06-06 02:33:37.762705::Ticker::B::Getting RAW data from BAC_quarterly_financial_data.csv::

In [239]:
stockpup_annual = stockpup.get_annual_data(stockpup_raw)

In [240]:
stockpup_annual

                   Shares  Shares split adjusted  Split factor         Assets  \
YEAR QUARTER
2017 4        10243688896            10243688896             1  2281234000000
     3        10430613675            10430613675             1  2283896000000
     2         9850580344             9850580344             1  2254529000000
     1         9951898904             9951898904             1  2247701000000
2016 4        10025121972            10025121972             1  2187702000000
...                   ...                    ...           ...            ...
1995 1          271404569             1085618276             4   183854000000
1994 4          276477155             1105908620             4   169604000000
     3          275621566             1102486264             4   170912000000
     2          276591985             1106367940             4   164398000000
     1          274715504             1098862016             4   165071000000

             Current Assets    Liabilities Current Liabilities  \
YEAR QUARTER
2017 4                 None  2014088000000                None
     3                 None  2011437000000                None
     2                 None  1983542000000                None
     1                 None  1979548000000                None
2016 4                 None  1920862000000                None
...                     ...            ...                 ...
1995 1                 None   172508000000                None
1994 4                 None   158593000000                None
     3                 None   160203000000                None
     2                 None   153925000000                None
     1                 None   154899000000                None

              Shareholders equity  Non-controlling interest  Preferred equity  \
YEAR QUARTER
2017 4               267146000000                         0                 0
     3               272459000000                         0                 0
     2               270987000000                         0                 0
     1               268153000000                         0                 0
2016 4               266840000000                         0                 0
...                           ...                       ...               ...
1995 1                11346000000                         0                 0
1994 4                11011000000                         0                 0
     3                10709000000                         0                 0
     2                10473000000                         0                 0
     1                10172000000                         0                 0

              ...  P/B ratio  P/E ratio Cumulative dividends per share  \
YEAR QUARTER  ...
2017 4        ...       1.06      14.79                          20.35
     3        ...       0.88      13.43                          20.23
     2        ...       0.86      13.69                          20.11
     1        ...       0.89      15.85                          20.04
2016 4        ...       0.73      16.16                          19.96
...           ...        ...        ...                            ...
1995 1        ...       1.21       7.95                           0.59
1994 4        ...       1.21       None                           0.47
     3        ...       1.36       None                           0.35
     2        ...       1.38       None                           0.23
     1        ...       1.29       None                           0.12

             Dividend payout ratio Long-term debt to equity ratio  \
YEAR QUARTER
2017 4                      0.2387                         0.8512
     3                      0.1764                         0.8393
     2                       0.157                         0.8263
     1                      0.1534                         0.8256
2016 4                      0.1593                         0.8126
...                            ...                            ...
1995 1                      0.3093                         0.0000
1994 4                      0.3087                         0.0000
     3                        None                         0.0000
     2                        None                         0.0000
     1                        None                         0.0000

             Equity to assets ratio Net margin  Asset turnover  \
YEAR QUARTER
2017 4                       0.1171     0.1902            0.04
     3                       0.1193     0.2252            0.04
     2                       0.1202     0.2182            0.04
     1                       0.1193     0.2124            0.04
2016 4                       0.1220     0.1938            0.04
...                             ...        ...             ...
1995 1                       0.0617     0.2168            0.05
1994 4                       0.0649     0.2152            0.05
     3                       0.0627       None            None
     2                       0.0637       None            None
     1                       0.0616       None            None

             Free cash flow per share Current ratio
YEAR QUARTER
2017 4                          -0.69          None
     3                           1.96          None
     2                              1          None
     1                          -1.29          None
2016 4                          -0.83          None
...                               ...           ...
1995 1                          -2.78          None
1994 4                          -0.67          None
     3                           2.83          None
     2                           1.53          None
     1                            4.3          None

[96 rows x 40 columns]